[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "Huid51EyAoXC4M1XLDDL756pRmmZZ1D7XCD3rowxX4hq"

[programs.devnet]
escrow = "Huid51EyAoXC4M1XLDDL756pRmmZZ1D7XCD3rowxX4hq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
